const char *VI_CONF = 
"mo global;"
"bi C-q signal KILL;"
"mo default;"
"bi Escape mo vi;"
"bi ^C wr goto-vi \\; mo vi;"
"bi ^C ^C ^C wr bye \\; wr bye \\; signal INT;"
"mo vi;"
"bi Escape mo default;"
"bi ^C wr goto-default \\; mo default;"
"bi ^C ^C ^C wr bye \\; wr bye \\; signal INT;"
"rep on;"
"bi : command;"
"bi h ke Left;"
"bi j ke Down;"
"bi k ke Up;"
"bi l ke Right;"
"bi C-d ke PageDown;"
"bi C-u ke PageUp;"
"bi 0 ke Home;"
"bi $ ke End;"
"bi g ke -r 10 PageUp;"
"bi G ke -r 10 PageDown;"
"bi w ke -r 6 Right;"
"bi e ke -r 4 Right;"
"bi b ke -r 4 Left;"
"bi B ke -r 8 Left;"
"bi x ke Delete;"
"bi d ke Delete;"
"bi D ke -r 80 Delete;"
"bi C ke -r 80 Delete \\; mo default;"
"bi i mo default;"
"bi a ke Right \\; mo default;"
"bi I ke C-a \\; mo default;"
"bi A ke C-e \\; mo default;"
"bi o ke Down \\; mo default;"
"bi O ke Up \\; mo default;"
;
