const char *VI_CONF = 
"mo default;"
"bi Escape go vi;"
"bi A-Escape go vi;"
"bi C-c go vi;"
"bi C-q signal INT;"
"mo vi;"
"re on;"
"bi C-c go global;"
"bi j ke Down;"
"bi k ke Up;"
"bi h ke Left;"
"bi l ke Right;"
"bi C-d ke PageDown;"
"bi C-u ke PageUp;"
"bi 0 ke Home;"
"bi $ ke End;"
"bi g ke -r 4 PageUp;"
"bi G ke -r 4 PageDown;"
"bi w ke -r 6 Right;"
"bi e ke -r 4 Right;"
"bi b ke -r 4 Left;"
"bi B ke -r 8 Left;"
"bi x ke Delete;"
"bi d ke Delete;"
"bi D ke -r 80 Delete;"
"bi C ke -r 80 Delete \\; go global;"
"bi i go global;"
"bi a ke Right \\; go global;"
"bi I ke C-a \\; go global;"
"bi A ke C-e \\; go global;"
"bi o ke Down \\; go global;"
"bi O ke Up \\; go global;"
;
