const char *VI_CONF = 
"mo global;"
"mo default;"
"b Escape mo vi;"
"b Escape Escape ke Escape;"
"b ^C mo vi;"
"b ^C ^C ke ^C;"
"unbo { reh||pa };"
"mo vi;"
"rep on ;"
"b Escape mo default;"
"b Escape Escape ke Escape;"
"b ^C mo default;"
"b ^C ^C ke ^C;"
"unbo any { reh||pa };"
"unbo char { reh||ig };"
"b h ke Left;"
"b j ke Down;"
"b k ke Up;"
"b l ke Right;"
"b C-d ke PageDown;"
"b C-u ke PageUp;"
"b 0 ke Home;"
"b $ ke End;"
"b g ke -r10 PageUp;"
"b G ke -r10 PageDown;"
"b w ke -r6 Right;"
"b e ke -r4 Right;"
"b b ke -r4 Left;"
"b B ke -r8 Left;"
"b x ke Delete;"
"b d ke Delete;"
"b D ke Delete;"
"b I rea -p \"> \";"
"b i rea -p \"> \";"
"b a rea -p \"> \";"
"b A rea -p \"> \";"
"b o rea -p \"> \";"
"b O rea -p \"> \";"
;
